config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :installs
  
  root "welcome#index"
  get "projetos", to: "welcome#projects", as: :projects
  get "sobre", to: "welcome#about", as: :about
  get "galeria", to: "welcome#gallery", as: :gallery
  get "usuario/:id", to: "users#show", as: :user

  resources :images
  post "images/new", to: "images#create", as: false

  get "favorite/new/:id", to: "favorite#new", as: :new_favorite
  post "favorite/new/:id", to: "favorite#create", as: false
  resources :favorite

  
  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	validates_uniqueness_of :user_id, scope: :image_id
end

app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing-picture.png"
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  	belongs_to :user
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :name, presence: true

  has_many :images
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :description
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController

	def new
		@image = Image.find params[:id]
		@add_favorite = Favorite.new
	end

	def create
		if current_user.coin >= 1
			@image = Image.find params[:id]
			
			@add_favorite = Favorite.create(favorite_params)
			@add_favorite.user_id = current_user.id
			@add_favorite.image_id = @image.id

			@owner = User.find_by id: @image.user_id
			@owner.coin = @owner.coin + 1

			current_user.coin = current_user.coin - 1	

			@image.favorite = @image.favorite + 1

			if @add_favorite.save && @owner.save && current_user.save && @image.save
				redirect_to user_path(current_user.id)	
			else
				render :new
			end
		else
			render :new
		end
	end

	def destroy
		@favorite = Favorite.find params[:id]
		@favorite.delete

		redirect_to user_path(current_user.id)
	end

	private 
	def favorite_params
		params.require(:favorite).permit(:user_id, :image_id);
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def new
		@new_img = Image.new
	end

	def create
		if current_user.coin >= 5
			@new_img = Image.create(images_params)
			@new_img.user_id = current_user.id	

			current_user.coin = current_user.coin - 5;


			if @new_img.save && current_user.save
				redirect_to user_path(current_user.id)
			else
				render :new
			end
		else
			redirect_to user_path(current_user.id)
		end
	end

	def destroy
		@image = Image.find params[:id]
		@image.delete

		current_user.coin = current_user.coin + 3

		redirect_to user_path(current_user.id)
	end

	private
	def images_params
		params.require(:image).permit(:user_id, :picture)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find params[:id]
        @images = @user.images
        @favorites = @user.favorites
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   
   def index
   end
   
   def projects
   end
   
   def about
   end

   def gallery
   		@images = Image.all
   end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

	def user_loged
        if current_user
            render "layouts/components_with_user"
        else
            render "layouts/components_without_user"
        end
    end

    def form_sign_up
    	unless current_user
    		render "welcome/form"
    	else
            render "welcome/disable_form"
        end
    end

    def image_status
        if current_user && $img.user_id == current_user.id
            render "users/image_status_adm"
        
        else
            render "users/image_status_other"
        end
    end
    
end

app/views/favorite/new.html.erb
<div class="container-form">

<h2>Adicionar aos Favoritos</h2>

<%= form_for @add_favorite, url: new_favorite_path  do |f| %>
	
  <div class="field">
  	<h4 style="color: red;">Atenção! Cada imagem adicionada aos favoritos lhe custará 1 estrela</h4>
  </div>

  <div class="field" style="display: none;">
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= image_tag @image.picture.url, style: "width: 100%;" %>
  </div>

  <div class="actions">
    <%= f.submit "Favoritar", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
  </div>
<% end %>

</div>

app/views/images/new.html.erb
<div class="container-form">

<h2>Adicionar imagem</h2>

<%= form_for @new_img, url: new_image_path  do |f| %>
	
  <div class="field">
  	<h4 style="color: red;">Atenção! Cada imagem adicionada tem um custo de 5 estrelas.</h4>
  	<p>Favoritar uma imagem custa 1 estrela.</p>
  </div>

  <div class="field">
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit "Adicionar", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
  </div>
<% end %>

</div>

app/views/layouts/_components_with_user.html.erb
<%= link_to current_user.name, user_path(current_user.id), class: "mdl-button mdl-js-button mdl-button--primary" %>
<%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent', style: "background: #e00;"  %>

app/views/layouts/_components_without_user.html.erb
<%= link_to "Login", new_user_session_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored'  %>
<%= link_to "Cadastre", new_user_registration_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holograma em vidro</title>
  
  <link rel="icon" href="<%= asset_path 'logo.png' %>">

  <!-- Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  <%= stylesheet_link_tag    'mdl', media: 'all', 'data-turbolinks-track' => true %>    
  <!-- MDL -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag    'material', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'material', 'data-turbolinks-track' => true %>
  <!-- end MDL -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'rwd-font', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
  <div class="side-left">
    <%= link_to root_path, style: "flex-grow: 0;" do |root| %>
      <%= image_tag "logo.png", style: "width: 35px;" %>
    <% end %>
    <h4>Holograma em vidro</h4>
  </div>
  
  <div class="side-right">
    <%= link_to "Projetos", projects_path, class: "mdl-button mdl-js-button mdl-js-ripple-effect", style: "color: #333" %>
    <%= link_to "Galeria", gallery_path, class: "mdl-button mdl-js-button mdl-js-ripple-effect", style: "color: #333" %>

    <%= user_loged %>
    
  </div>
</nav>

<a href="#" onclick="Menu()" style="color: black" class="menu-button">
  <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" style="width: 6em; height: 6em;">
    <i class="material-icons md-48" style="left: 0.55em; font-size: 80px;">menu</i>
  </button>
</a>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<footer>
  <small>@2016 - Holograma em Virdro</small>
</footer>

</body>
</html>

app/views/users/_image_status_adm.html.erb
<div class="image-status">
	<a href="#">
		<%= image_tag "star-icon.png" %>
		<%= $img.favorite %>
	</a>

	<a href="#">
		<%= image_tag "garbage.png" %>
		<%= link_to "Deletar", image_path($img.id), method: :delete %>
	</a>
</div>

app/views/users/_image_status_other.html.erb
<div class="image-status">
	<a href="#">
		<%= image_tag "star-icon.png" %>
		<%= $img.favorite %>
	</a>

	<% unless (Favorite.find_by image_id: $img.id) && (Favorite.find_by user_id: current_user.id) %>
		<a href="#">
			<%= image_tag "favorite.png" %>
			<%= link_to "Favoritar", new_favorite_path($img.id) %>
		</a>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="user-profile">

	<%= image_tag @user.avatar.url, class: "avatar" if @user.avatar.url %>

	<h1><%= @user.name %></h1>

	<!-- Container to status and description -->
	<div class="container-sd">
		<% if current_user && current_user.id == @user.id %>
		<div class="status-bar">
			<span>
				<%= image_tag "star-icon.png", class: "star-icon" %>
				<p><%= @user.coin %></p>
			</span>
			
			<%= link_to 'Editar perfil', edit_user_registration_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", style: "width: 150px; background: orange;"%>
		</div>
		<% end %>
		<div class="user-description">
			<p>
				<%= @user.description %>
			</p>
		</div>
	</div>

</div>

<h2>Galeria pessoal</h2>

<%= link_to "Adicionar nova imagem", new_image_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", style: "width: 200px;" %>

<div class="container-gallery">

	<% @favorites.reverse.each do |fav| %>
		<% @img = Image.find_by id: fav.image_id %>
		<% if @img %>
			<div class="container-image">
				<%= image_tag @img.picture.url %>
				<% $img = @img %>
				<%= image_status %>
			</div>
		<% end %>
	<% end %>

	<% @images.reverse.each do |img| %>
		<div class="container-image">
			<%= image_tag img.picture.url %>
			<% $img = img %>
			<%= image_status %>
		</div>	
	<% end %>

	<div class="container-image">
		<%= image_tag "character.gif" %>
		<div class="image-status">
			<a href="#">
				<%= image_tag "star-icon.png" %>
				9999
			</a>
		</div>
	</div>

	<div class="container-image">
		<%= image_tag "passaro.jpg" %>
		<div class="image-status">
			<a href="#">
				<%= image_tag "star-icon.png" %>
				9999
			</a>
		</div>
	</div>

	<div class="container-image">
		<%= image_tag "warrior.gif" %>
		<div class="image-status">
			<a href="#">
				<%= image_tag "star-icon.png" %>
				9999
			</a>
		</div>
	</div>

</div>

app/views/welcome/_disable_form.html.erb
<div class="form" style="opacity: 0;">
    <%= form_for(:user, :url => registration_path(:user)) do |f| %>
    <p>
        Nome:<br>
        <%= f.text_field :name, autofocus: true, disabled: true %>
    </p>
    <p>
        E-mail:<br>
        <%= f.email_field :email, autofocus: true, disabled: true %>
    </p>
    <p> 
        Senha:<br>
        <%= f.password_field :password, autocomplete: "off", disabled: true %>
    </p>
    <p>
        Confirmar senha:<br>
        <%= f.password_field :password_confirmation, autocomplete: "off", disabled: true %>
    </p>
        <%= f.submit "Cadastrar", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", disabled: true %>
    <% end %>
</div>

app/views/welcome/_form.html.erb
<div class="form">
    <%= form_for(:user, :url => registration_path(:user)) do |f| %>
    <p>
        Nome:<br>
        <%= f.text_field :name, autofocus: true %>
    </p>
    <p>
        E-mail:<br>
        <%= f.email_field :email, autofocus: true %>
    </p>
    <p> 
        Senha:<br>
        <%= f.password_field :password, autocomplete: "off" %>
    </p>
    <p>
        Confirmar senha:<br>
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </p>
        <%= f.submit "Cadastrar", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
    <% end %>
</div>

app/views/welcome/gallery.html.erb
<h1>Galeria</h1>

<div class="container-gallery">
	<% @images.reverse.each do |img| %>
		<div class="container-image">
			<%= image_tag img.picture.url %>
			<% $img = img %>
			<%= image_status %>
		</div>	
	<% end %>
</div>

app/views/welcome/index.html.erb
<header>
    <!-- FOR MORE SPEED -->
    <!--<video loop muted autoplay class="fullscreen-bg__video">-->
    <!--    <source src="<%= asset_path "bg.mp4" %>" type="video/mp4">-->
    <!--</video>-->
    
    <div class="context">
        <h1 class="title">Projete em seu holograma</h1>    
        <p>Aqui você encontrará imagens e vídeos para seu holograma em vidro, além de criar expor sua própria galeria compartilhada.
        </p>
    </div>
    
    <%= form_sign_up %>
</header>

<div class="features">
    <h4>
        Totalmente gratuito para todos!
    </h4>
    
    <p>
        Todos os serviços oferecidos pelo site são completamente gratuitos. Cadastre-se e desfrute da galeria de imagens e vídeos e compartilhe suas ideias com todos.
    </p>
</div>

<div class="about">
    <h2 class="title">
        Sejam bem vindos!
    </h2>
    
    <p>
        O Site Holograma em vidro permite você postar seus vídeos e imagens para compartilhamento entre outros usuários ou apenas guardá-los para si próprio, mantendo seu entretenimento e privacidade ao máximo.
    </p>
</div>

<div class="services">
    <div>
        <%= image_tag "share-icon.png"%>
        <h5>Compartilhe com todos</h5>
        
        <p>
            Faça o upload de suas imagens e vídeos para que todos possam vê-los, e visualize em tempo real novas postagens pelo seu Feed de notícias.
        </p>
    </div>
    <div class="mid-panel-cl">
        <%= image_tag "locked-icon.png"%>
        <h5>Tenha privacidade</h5>
        
        <p>
            A opção “somente eu” servirá para você publicar suas imagens em modo privado, podendo deixá-las apenas a sua disposição.
        </p>
    </div>
    <div class="mid-panel-cr mid-panel-cl">
        <%= image_tag "gallery-icon.png"%>
        <h5>Galeria completa</h5>
        
        <p>
            Faça sua pró pia galeria de imagens fazendo upload de suas pró pias imagens ou favoritando imagens de outros usuários.
        </p>
    </div>
    <div>
        <%= image_tag "coin-icon.png"%>
        <h5>Sistema de moedas</h5>
        
        <p>
            Fique virtualmente rico dentro do sistema de moedas, onde imagens não são apenas imagens, e seu trabalho é valorizado.
        </p>
    </div>
</div>
<h2 class="peoples-use title">Quem usa holografia?</h2><br>
<div class="users">
    
    <div>
        <h4 class="border-blue">Pessoas fisicas ></h4>
        <p>
            Crie seus projetos, imagens e vídeos para uso somente pessoal ou compartilhe com todos os usuários do Holograma em vidro.
        </p>
    </div>
    <div>
        <h4 class="border-red">Professores | Palestrantes ></h4>
        <p>
            Apresente de forma diferente alguns conteúdos para seus alunos, fazendo terem uma sensação de vídeo em 3D, apresentando trabalhos e fazendo atividades baseadas em suas criatividades.
        </p>
    </div>
    <div>
        <h4 class="border-gray">Empresários ></h4>
        <p>
            Divulgue suas criações pelo Holograma em vidro, grandes empresas estão investindo nesta idéia, use e abuse do projeto para mais conhecimento sobre o Holograma em vidro e tenha inspiração para seus projetos.
        </p>
    </div>
</div>

<div class="company">
    <div>
        <%= image_tag "demo.jpg" %>    
    </div>
    
    <div><br>
        <h4>
            Holograma em vidro já foi usado por grandes empresas como a Samsung e a Coca-cola.
        </h4>    
    </div>
    
</div>

app/views/welcome/projects.html.erb
<div class="projects">
    <div class="project carousel-1" id="carousel-1" target="framename">
        <a href="#carousel-3"><%= image_tag "carousel-arrow.png", class: "carousel-back carousel-arrow" %></a>
        <%= image_tag "pyramid-4faces.png", class: "project-image" %>
        <div>
            <h2>Pirâmide - 4 Faces</h2>
            <p>
                A pirâmide de quatro faces é o projeto mais conhecido entre os projetos de holografia. Além de sua simplicidade, as quatro faces do projeto apresentam uma maior imersão da imagem em nossa realidade, proporcionando aos usuários uma incrível experiência com o 3D. Para utiliza-lo é necessário ter um vídeo ou imagem pré-programado com quatro vista diferentes, uma para cada lado. O projeto utiliza tanto tablets como smartphones.
            </p>
        </div>
        <a href="#carousel-2"><%= image_tag "carousel-arrow.png", class: "carousel-next carousel-arrow" %></a>
    </div>
    <div class="project carousel-2" id="carousel-2">
        <a href="#carousel-1"><%= image_tag "carousel-arrow.png", class: "carousel-back carousel-arrow" %></a>
        <%= image_tag "pyramid-3faces.png", class: "project-image" %>
        <div>
            <h2>Pirâmide - 3 Faces</h2>
            <p>
                O projeto pirâmide de três faces traz uma nova demonstração, apresentando um visual mais profissional. A experiência é muito parecida com a pirâmide de quatro faces. O projeto também pode ser utilizado com tablets e smartphones e por sua vez deve ter um vídeo ou imagem bem elaborada com três lados distintos para forma a imagem em três dimensões.
            </p>
        </div>
        <a href="#carousel-3"><%= image_tag "carousel-arrow.png", class: "carousel-next carousel-arrow" %></a>
    </div>
    <div class="project carousel-3" id="carousel-3">
        <a href="#carousel-2"><%= image_tag "carousel-arrow.png", class: "carousel-back carousel-arrow" %></a>
        <%= image_tag "zed-1face.jpg", class: "project-image" %>
        <div>
            <h2>Zed - 1 Face</h2>
            <p>
                O projeto de apenas uma face, também conhecido como Zed devido ao seu formato em “Z”, é o mais simples, podendo ser utilizado facilmente para qualquer tipo de vídeo ou imagem sem necessidade de grandes alterações para se ter a perspectiva 3D. Assim como os outros modelos, o Zed também é compatível com tablets e smatphones.
            </p>
        </div>
        <a href="#carousel-1"><%= image_tag "carousel-arrow.png", class: "carousel-next carousel-arrow" %></a>
    </div>
</div>

<script>
    window.location = "#carousel-1";
</script>